//
//Copyright 2020 The Magma Authors.
//
//This source code is licensed under the BSD-style license found in the
//LICENSE file in the root directory of this source tree.
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

//
// This is a proxy for Diamater application S6a/S6d 3GPP 29.272
// It is watered down for use with OpenAirInterface EPC with extensibility in mind
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: lte/protos/subscriberauth.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode reflects Experimental-Result values which are 3GPP failures
// to be processed by EPC. Diameter Base Protocol errors are reflected in gRPC status code
type M5GErrorCode int32

const (
	M5GErrorCode_UNDEFINED M5GErrorCode = 0
	// Default success code
	M5GErrorCode_MULTI_ROUND_AUTH        M5GErrorCode = 1001
	M5GErrorCode_SUCCESS                 M5GErrorCode = 2001
	M5GErrorCode_LIMITED_SUCCESS         M5GErrorCode = 2002
	M5GErrorCode_COMMAND_UNSUPORTED      M5GErrorCode = 3001
	M5GErrorCode_UNABLE_TO_DELIVER       M5GErrorCode = 3002
	M5GErrorCode_REALM_NOT_SERVED        M5GErrorCode = 3003
	M5GErrorCode_TOO_BUSY                M5GErrorCode = 3004
	M5GErrorCode_LOOP_DETECTED           M5GErrorCode = 3005
	M5GErrorCode_REDIRECT_INDICATION     M5GErrorCode = 3006
	M5GErrorCode_APPLICATION_UNSUPPORTED M5GErrorCode = 3007
	M5GErrorCode_INVALIDH_DR_BITS        M5GErrorCode = 3008
	M5GErrorCode_INVALID_AVP_BITS        M5GErrorCode = 3009
	M5GErrorCode_UNKNOWN_PEER            M5GErrorCode = 3010
	M5GErrorCode_AUTHENTICATION_REJECTED M5GErrorCode = 4001
	M5GErrorCode_OUT_OF_SPACE            M5GErrorCode = 4002
	M5GErrorCode_ELECTION_LOST           M5GErrorCode = 4003
	M5GErrorCode_AUTHORIZATION_REJECTED  M5GErrorCode = 5003
	// Permanent Failures 7.4.3
	M5GErrorCode_USER_UNKNOWN             M5GErrorCode = 5001
	M5GErrorCode_UNKNOWN_SESSION_ID       M5GErrorCode = 5002
	M5GErrorCode_UNKNOWN_EPS_SUBSCRIPTION M5GErrorCode = 5420
	M5GErrorCode_RAT_NOT_ALLOWED          M5GErrorCode = 5421
	M5GErrorCode_ROAMING_NOT_ALLOWED      M5GErrorCode = 5004
	M5GErrorCode_EQUIPMENT_UNKNOWN        M5GErrorCode = 5422
	M5GErrorCode_UNKNOWN_SERVING_NODE     M5GErrorCode = 5423
	// Transient Failures 7.4.4
	M5GErrorCode_AUTHENTICATION_DATA_UNAVAILABLE M5GErrorCode = 4181
)

// Enum value maps for M5GErrorCode.
var (
	M5GErrorCode_name = map[int32]string{
		0:    "UNDEFINED",
		1001: "MULTI_ROUND_AUTH",
		2001: "SUCCESS",
		2002: "LIMITED_SUCCESS",
		3001: "COMMAND_UNSUPORTED",
		3002: "UNABLE_TO_DELIVER",
		3003: "REALM_NOT_SERVED",
		3004: "TOO_BUSY",
		3005: "LOOP_DETECTED",
		3006: "REDIRECT_INDICATION",
		3007: "APPLICATION_UNSUPPORTED",
		3008: "INVALIDH_DR_BITS",
		3009: "INVALID_AVP_BITS",
		3010: "UNKNOWN_PEER",
		4001: "AUTHENTICATION_REJECTED",
		4002: "OUT_OF_SPACE",
		4003: "ELECTION_LOST",
		5003: "AUTHORIZATION_REJECTED",
		5001: "USER_UNKNOWN",
		5002: "UNKNOWN_SESSION_ID",
		5420: "UNKNOWN_EPS_SUBSCRIPTION",
		5421: "RAT_NOT_ALLOWED",
		5004: "ROAMING_NOT_ALLOWED",
		5422: "EQUIPMENT_UNKNOWN",
		5423: "UNKNOWN_SERVING_NODE",
		4181: "AUTHENTICATION_DATA_UNAVAILABLE",
	}
	M5GErrorCode_value = map[string]int32{
		"UNDEFINED":                       0,
		"MULTI_ROUND_AUTH":                1001,
		"SUCCESS":                         2001,
		"LIMITED_SUCCESS":                 2002,
		"COMMAND_UNSUPORTED":              3001,
		"UNABLE_TO_DELIVER":               3002,
		"REALM_NOT_SERVED":                3003,
		"TOO_BUSY":                        3004,
		"LOOP_DETECTED":                   3005,
		"REDIRECT_INDICATION":             3006,
		"APPLICATION_UNSUPPORTED":         3007,
		"INVALIDH_DR_BITS":                3008,
		"INVALID_AVP_BITS":                3009,
		"UNKNOWN_PEER":                    3010,
		"AUTHENTICATION_REJECTED":         4001,
		"OUT_OF_SPACE":                    4002,
		"ELECTION_LOST":                   4003,
		"AUTHORIZATION_REJECTED":          5003,
		"USER_UNKNOWN":                    5001,
		"UNKNOWN_SESSION_ID":              5002,
		"UNKNOWN_EPS_SUBSCRIPTION":        5420,
		"RAT_NOT_ALLOWED":                 5421,
		"ROAMING_NOT_ALLOWED":             5004,
		"EQUIPMENT_UNKNOWN":               5422,
		"UNKNOWN_SERVING_NODE":            5423,
		"AUTHENTICATION_DATA_UNAVAILABLE": 4181,
	}
)

func (x M5GErrorCode) Enum() *M5GErrorCode {
	p := new(M5GErrorCode)
	*p = x
	return p
}

func (x M5GErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (M5GErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lte_protos_subscriberauth_proto_enumTypes[0].Descriptor()
}

func (M5GErrorCode) Type() protoreflect.EnumType {
	return &file_lte_protos_subscriberauth_proto_enumTypes[0]
}

func (x M5GErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use M5GErrorCode.Descriptor instead.
func (M5GErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_lte_protos_subscriberauth_proto_rawDescGZIP(), []int{0}
}

// Authentication Information Request (Section 7.2.5)
type M5GAuthenticationInformationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Subscriber identifier
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	// Resync related information
	ResyncInfo []byte `protobuf:"bytes,2,opt,name=resync_info,json=resyncInfo,proto3" json:"resync_info,omitempty"`
	// Name of the serving network (snni)
	ServingNetworkName string `protobuf:"bytes,3,opt,name=serving_network_name,json=servingNetworkName,proto3" json:"serving_network_name,omitempty"`
}

func (x *M5GAuthenticationInformationRequest) Reset() {
	*x = M5GAuthenticationInformationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_subscriberauth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M5GAuthenticationInformationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M5GAuthenticationInformationRequest) ProtoMessage() {}

func (x *M5GAuthenticationInformationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_subscriberauth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M5GAuthenticationInformationRequest.ProtoReflect.Descriptor instead.
func (*M5GAuthenticationInformationRequest) Descriptor() ([]byte, []int) {
	return file_lte_protos_subscriberauth_proto_rawDescGZIP(), []int{0}
}

func (x *M5GAuthenticationInformationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *M5GAuthenticationInformationRequest) GetResyncInfo() []byte {
	if x != nil {
		return x.ResyncInfo
	}
	return nil
}

func (x *M5GAuthenticationInformationRequest) GetServingNetworkName() string {
	if x != nil {
		return x.ServingNetworkName
	}
	return ""
}

// Authentication Information Answer (Section 7.2.6)
type M5GAuthenticationInformationAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EPC error code on failure
	ErrorCode M5GErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=magma.lte.M5GErrorCode" json:"error_code,omitempty"`
	// Authentication vectors matching the requested number
	M5GauthVectors []*M5GAuthenticationInformationAnswer_M5GAuthenticationVector `protobuf:"bytes,2,rep,name=m5gauth_vectors,json=m5gauthVectors,proto3" json:"m5gauth_vectors,omitempty"`
}

func (x *M5GAuthenticationInformationAnswer) Reset() {
	*x = M5GAuthenticationInformationAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_subscriberauth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M5GAuthenticationInformationAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M5GAuthenticationInformationAnswer) ProtoMessage() {}

func (x *M5GAuthenticationInformationAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_subscriberauth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M5GAuthenticationInformationAnswer.ProtoReflect.Descriptor instead.
func (*M5GAuthenticationInformationAnswer) Descriptor() ([]byte, []int) {
	return file_lte_protos_subscriberauth_proto_rawDescGZIP(), []int{1}
}

func (x *M5GAuthenticationInformationAnswer) GetErrorCode() M5GErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return M5GErrorCode_UNDEFINED
}

func (x *M5GAuthenticationInformationAnswer) GetM5GauthVectors() []*M5GAuthenticationInformationAnswer_M5GAuthenticationVector {
	if x != nil {
		return x.M5GauthVectors
	}
	return nil
}

// 3GPP TS 29.272, 7.3.18 E-UTRAN-Vector
// For details about fields read 3GPP 33.401
type M5GAuthenticationInformationAnswer_M5GAuthenticationVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rand     []byte `protobuf:"bytes,1,opt,name=rand,proto3" json:"rand,omitempty"`
	XresStar []byte `protobuf:"bytes,2,opt,name=xres_star,json=xresStar,proto3" json:"xres_star,omitempty"`
	Autn     []byte `protobuf:"bytes,3,opt,name=autn,proto3" json:"autn,omitempty"`
	Kseaf    []byte `protobuf:"bytes,4,opt,name=kseaf,proto3" json:"kseaf,omitempty"`
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) Reset() {
	*x = M5GAuthenticationInformationAnswer_M5GAuthenticationVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lte_protos_subscriberauth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M5GAuthenticationInformationAnswer_M5GAuthenticationVector) ProtoMessage() {}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) ProtoReflect() protoreflect.Message {
	mi := &file_lte_protos_subscriberauth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M5GAuthenticationInformationAnswer_M5GAuthenticationVector.ProtoReflect.Descriptor instead.
func (*M5GAuthenticationInformationAnswer_M5GAuthenticationVector) Descriptor() ([]byte, []int) {
	return file_lte_protos_subscriberauth_proto_rawDescGZIP(), []int{1, 0}
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetRand() []byte {
	if x != nil {
		return x.Rand
	}
	return nil
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetXresStar() []byte {
	if x != nil {
		return x.XresStar
	}
	return nil
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetAutn() []byte {
	if x != nil {
		return x.Autn
	}
	return nil
}

func (x *M5GAuthenticationInformationAnswer_M5GAuthenticationVector) GetKseaf() []byte {
	if x != nil {
		return x.Kseaf
	}
	return nil
}

var File_lte_protos_subscriberauth_proto protoreflect.FileDescriptor

var file_lte_protos_subscriberauth_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6c, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x22, 0x95, 0x01, 0x0a,
	0x23, 0x4d, 0x35, 0x47, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x30, 0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x12, 0x73, 0x65, 0x72, 0x76, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc2, 0x02, 0x0a, 0x22, 0x4d, 0x35, 0x47, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x4d, 0x35, 0x47, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x6e, 0x0a, 0x0f, 0x6d, 0x35, 0x67, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x76,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x45, 0x2e, 0x6d,
	0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x4d, 0x35, 0x47, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2e, 0x4d, 0x35, 0x47, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x0e, 0x6d, 0x35, 0x67, 0x61, 0x75, 0x74, 0x68, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x1a, 0x74, 0x0a, 0x17, 0x4d, 0x35, 0x47, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x61,
	0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x78, 0x72, 0x65, 0x73, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x78, 0x72, 0x65, 0x73, 0x53, 0x74, 0x61, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61,
	0x75, 0x74, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6b, 0x73, 0x65, 0x61, 0x66, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x6b, 0x73, 0x65, 0x61, 0x66, 0x2a, 0xf2, 0x04, 0x0a, 0x0c, 0x4d, 0x35,
	0x47, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x10, 0x4d, 0x55, 0x4c,
	0x54, 0x49, 0x5f, 0x52, 0x4f, 0x55, 0x4e, 0x44, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x10, 0xe9, 0x07,
	0x12, 0x0c, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0xd1, 0x0f, 0x12, 0x14,
	0x0a, 0x0f, 0x4c, 0x49, 0x4d, 0x49, 0x54, 0x45, 0x44, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53,
	0x53, 0x10, 0xd2, 0x0f, 0x12, 0x17, 0x0a, 0x12, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x5f,
	0x55, 0x4e, 0x53, 0x55, 0x50, 0x4f, 0x52, 0x54, 0x45, 0x44, 0x10, 0xb9, 0x17, 0x12, 0x16, 0x0a,
	0x11, 0x55, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x44, 0x45, 0x4c, 0x49, 0x56,
	0x45, 0x52, 0x10, 0xba, 0x17, 0x12, 0x15, 0x0a, 0x10, 0x52, 0x45, 0x41, 0x4c, 0x4d, 0x5f, 0x4e,
	0x4f, 0x54, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x44, 0x10, 0xbb, 0x17, 0x12, 0x0d, 0x0a, 0x08,
	0x54, 0x4f, 0x4f, 0x5f, 0x42, 0x55, 0x53, 0x59, 0x10, 0xbc, 0x17, 0x12, 0x12, 0x0a, 0x0d, 0x4c,
	0x4f, 0x4f, 0x50, 0x5f, 0x44, 0x45, 0x54, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0xbd, 0x17, 0x12,
	0x18, 0x0a, 0x13, 0x52, 0x45, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x5f, 0x49, 0x4e, 0x44, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0xbe, 0x17, 0x12, 0x1c, 0x0a, 0x17, 0x41, 0x50, 0x50,
	0x4c, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x55, 0x50, 0x50, 0x4f,
	0x52, 0x54, 0x45, 0x44, 0x10, 0xbf, 0x17, 0x12, 0x15, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x48, 0x5f, 0x44, 0x52, 0x5f, 0x42, 0x49, 0x54, 0x53, 0x10, 0xc0, 0x17, 0x12, 0x15,
	0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x56, 0x50, 0x5f, 0x42, 0x49,
	0x54, 0x53, 0x10, 0xc1, 0x17, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x5f, 0x50, 0x45, 0x45, 0x52, 0x10, 0xc2, 0x17, 0x12, 0x1c, 0x0a, 0x17, 0x41, 0x55, 0x54, 0x48,
	0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43,
	0x54, 0x45, 0x44, 0x10, 0xa1, 0x1f, 0x12, 0x11, 0x0a, 0x0c, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46,
	0x5f, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0xa2, 0x1f, 0x12, 0x12, 0x0a, 0x0d, 0x45, 0x4c, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c, 0x4f, 0x53, 0x54, 0x10, 0xa3, 0x1f, 0x12, 0x1b, 0x0a,
	0x16, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52,
	0x45, 0x4a, 0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x8b, 0x27, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x89, 0x27, 0x12, 0x17, 0x0a,
	0x12, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e,
	0x5f, 0x49, 0x44, 0x10, 0x8a, 0x27, 0x12, 0x1d, 0x0a, 0x18, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x5f, 0x45, 0x50, 0x53, 0x5f, 0x53, 0x55, 0x42, 0x53, 0x43, 0x52, 0x49, 0x50, 0x54, 0x49,
	0x4f, 0x4e, 0x10, 0xac, 0x2a, 0x12, 0x14, 0x0a, 0x0f, 0x52, 0x41, 0x54, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x45, 0x44, 0x10, 0xad, 0x2a, 0x12, 0x18, 0x0a, 0x13, 0x52,
	0x4f, 0x41, 0x4d, 0x49, 0x4e, 0x47, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57,
	0x45, 0x44, 0x10, 0x8c, 0x27, 0x12, 0x16, 0x0a, 0x11, 0x45, 0x51, 0x55, 0x49, 0x50, 0x4d, 0x45,
	0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0xae, 0x2a, 0x12, 0x19, 0x0a,
	0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x4e, 0x47,
	0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0xaf, 0x2a, 0x12, 0x24, 0x0a, 0x1f, 0x41, 0x55, 0x54, 0x48,
	0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0xd5, 0x20, 0x32, 0x9e,
	0x01, 0x0a, 0x1b, 0x4d, 0x35, 0x47, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72,
	0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x7f,
	0x0a, 0x1c, 0x4d, 0x35, 0x47, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x4d, 0x35, 0x47, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2e, 0x6c, 0x74, 0x65, 0x2e, 0x4d, 0x35, 0x47, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x00, 0x42,
	0x1b, 0x5a, 0x19, 0x6d, 0x61, 0x67, 0x6d, 0x61, 0x2f, 0x6c, 0x74, 0x65, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lte_protos_subscriberauth_proto_rawDescOnce sync.Once
	file_lte_protos_subscriberauth_proto_rawDescData = file_lte_protos_subscriberauth_proto_rawDesc
)

func file_lte_protos_subscriberauth_proto_rawDescGZIP() []byte {
	file_lte_protos_subscriberauth_proto_rawDescOnce.Do(func() {
		file_lte_protos_subscriberauth_proto_rawDescData = protoimpl.X.CompressGZIP(file_lte_protos_subscriberauth_proto_rawDescData)
	})
	return file_lte_protos_subscriberauth_proto_rawDescData
}

var file_lte_protos_subscriberauth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lte_protos_subscriberauth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lte_protos_subscriberauth_proto_goTypes = []interface{}{
	(M5GErrorCode)(0), // 0: magma.lte.M5GErrorCode
	(*M5GAuthenticationInformationRequest)(nil),                        // 1: magma.lte.M5GAuthenticationInformationRequest
	(*M5GAuthenticationInformationAnswer)(nil),                         // 2: magma.lte.M5GAuthenticationInformationAnswer
	(*M5GAuthenticationInformationAnswer_M5GAuthenticationVector)(nil), // 3: magma.lte.M5GAuthenticationInformationAnswer.M5GAuthenticationVector
}
var file_lte_protos_subscriberauth_proto_depIdxs = []int32{
	0, // 0: magma.lte.M5GAuthenticationInformationAnswer.error_code:type_name -> magma.lte.M5GErrorCode
	3, // 1: magma.lte.M5GAuthenticationInformationAnswer.m5gauth_vectors:type_name -> magma.lte.M5GAuthenticationInformationAnswer.M5GAuthenticationVector
	1, // 2: magma.lte.M5GSubscriberAuthentication.M5GAuthenticationInformation:input_type -> magma.lte.M5GAuthenticationInformationRequest
	2, // 3: magma.lte.M5GSubscriberAuthentication.M5GAuthenticationInformation:output_type -> magma.lte.M5GAuthenticationInformationAnswer
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_lte_protos_subscriberauth_proto_init() }
func file_lte_protos_subscriberauth_proto_init() {
	if File_lte_protos_subscriberauth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lte_protos_subscriberauth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M5GAuthenticationInformationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_subscriberauth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M5GAuthenticationInformationAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lte_protos_subscriberauth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*M5GAuthenticationInformationAnswer_M5GAuthenticationVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lte_protos_subscriberauth_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lte_protos_subscriberauth_proto_goTypes,
		DependencyIndexes: file_lte_protos_subscriberauth_proto_depIdxs,
		EnumInfos:         file_lte_protos_subscriberauth_proto_enumTypes,
		MessageInfos:      file_lte_protos_subscriberauth_proto_msgTypes,
	}.Build()
	File_lte_protos_subscriberauth_proto = out.File
	file_lte_protos_subscriberauth_proto_rawDesc = nil
	file_lte_protos_subscriberauth_proto_goTypes = nil
	file_lte_protos_subscriberauth_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// M5GSubscriberAuthenticationClient is the client API for M5GSubscriberAuthentication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type M5GSubscriberAuthenticationClient interface {
	// Authentication-Information (Code 318)
	M5GAuthenticationInformation(ctx context.Context, in *M5GAuthenticationInformationRequest, opts ...grpc.CallOption) (*M5GAuthenticationInformationAnswer, error)
}

type m5GSubscriberAuthenticationClient struct {
	cc grpc.ClientConnInterface
}

func NewM5GSubscriberAuthenticationClient(cc grpc.ClientConnInterface) M5GSubscriberAuthenticationClient {
	return &m5GSubscriberAuthenticationClient{cc}
}

func (c *m5GSubscriberAuthenticationClient) M5GAuthenticationInformation(ctx context.Context, in *M5GAuthenticationInformationRequest, opts ...grpc.CallOption) (*M5GAuthenticationInformationAnswer, error) {
	out := new(M5GAuthenticationInformationAnswer)
	err := c.cc.Invoke(ctx, "/magma.lte.M5GSubscriberAuthentication/M5GAuthenticationInformation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// M5GSubscriberAuthenticationServer is the server API for M5GSubscriberAuthentication service.
type M5GSubscriberAuthenticationServer interface {
	// Authentication-Information (Code 318)
	M5GAuthenticationInformation(context.Context, *M5GAuthenticationInformationRequest) (*M5GAuthenticationInformationAnswer, error)
}

// UnimplementedM5GSubscriberAuthenticationServer can be embedded to have forward compatible implementations.
type UnimplementedM5GSubscriberAuthenticationServer struct {
}

func (*UnimplementedM5GSubscriberAuthenticationServer) M5GAuthenticationInformation(context.Context, *M5GAuthenticationInformationRequest) (*M5GAuthenticationInformationAnswer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method M5GAuthenticationInformation not implemented")
}

func RegisterM5GSubscriberAuthenticationServer(s *grpc.Server, srv M5GSubscriberAuthenticationServer) {
	s.RegisterService(&_M5GSubscriberAuthentication_serviceDesc, srv)
}

func _M5GSubscriberAuthentication_M5GAuthenticationInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(M5GAuthenticationInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(M5GSubscriberAuthenticationServer).M5GAuthenticationInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/magma.lte.M5GSubscriberAuthentication/M5GAuthenticationInformation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(M5GSubscriberAuthenticationServer).M5GAuthenticationInformation(ctx, req.(*M5GAuthenticationInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _M5GSubscriberAuthentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "magma.lte.M5GSubscriberAuthentication",
	HandlerType: (*M5GSubscriberAuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "M5GAuthenticationInformation",
			Handler:    _M5GSubscriberAuthentication_M5GAuthenticationInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lte/protos/subscriberauth.proto",
}
